# Config file for automatic testing at travis-ci.org

dist: xenial
language: python
python:
  - "3.6"
  - "3.7"

install: pip install tox-travis poetry # codecov

script: tox

# after_success: codecov

jobs:
  include:
    - stage: deploy
      script: poetry publish --build --username sneakypete81 --password $PYPI_PASS

stages:
  - test
  - name: deploy
    if: tag IS present AND repo = sneakypete81/phink

env:
  global:
  - secure: lU4zD9Mc2OkidSsquoFbtzbDOQNYxbRd4CcQJ17YhGUahAEj5fkOu6f+mHui1eL7evzCfVEI6vM7in6ZtwUZaOvLM1Ncdm8Nmq+cfXPhQPVqaGuSQ9bCNA/2ovNFFYQ+tdJ0rKNmoP0ErHaXR2OmFL35DYtHOuhtv0OxDR3AgL3Q8CTtY2eD8bWPZ89+xAD7EcdegydubDwo5oP61nN06I5ZK+XiOxQahVonxem9x/CdWdteCprPjKBHwBLPY1anW3AJ5gJYex4mbcYk0VfZUHpU3kY9cHRCc0di6x3XhSb6HHf3afDSuXSfqK4ecy/dLI2VhQzc6dGg+XJa/g1l9PhIZj+DTjAMjO3sh/MhSAEV8VHnIliRvtHQCmqrqLlOmz0kNiPOKzxgh7+anM/18jdQUxACqFMbbta7LAUsJnt9V9WoT5fN2DamsqazZIwbcOkUYY1Zf1fIbctNnJI4V1sflwtw9KwrIZ5SvPOoOnTfWsWBwjDjXK8y2PNs6VPc0+F3NKYGf7JmEsmOaawEquUQJ7feV/UXAwO0kdhpnvRa4VGXe+sztbWO5B1nCW//3nQLuKneITohFoBEUrkeRcKhVZfjbjaZpsoNX/GehFeFFzVsxWCzuRTprFO73CsJYH9NKBEbKWikBBVTDlst1D4J9TDT5CVbi6ff6Qw75Po=
